logging:
  level:
    org:
      springframework:
        security: 'DEBUG'
      hibernate:
        SQL: 'DEBUG'
#Specifying the application name
spring:
  application:
    name: greenspaces
  #establish connection to mysql database
  datasource:
    driverClassName: 'org.h2.Driver'
    url: jdbc:h2:mem:greenspaces-testdb'
    username: 'greenspaces'
    password: 'greenspaces'
  jpa:
    hibernate:
      ddl-auto: 'none'
    show-sql: true

    database-platform: 'org.hibernate.dialect.H2Dialect'
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:/data.sql
      schema-locations: classpath:/schema.sql
      mode: always


